name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        # Set Git username and email
        git config --global user.name "Bilal-Anjum123"
        git config --global user.email "bilalanjum.ds@gmail.com"
        
        # Install Git LFS
        git lfs install
        
        # Clone the Hugging Face Space repository
        git clone https://huggingface.co/spaces/Bilal-Anjum/ML-App
        
        cd ML-App

        # Pull the latest changes
        git pull origin main

        # Copy files to the Hugging Face Space directory

        rsync -av --exclude ML-App/ ../ ./

        

        # Stage all changes
        git add .
        
        # Commit changes (ignore empty commits)
        git commit -m "Update Hugging Face Space" || echo "No changes to commit"
                
        git push --force https://user:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Bilal-Anjum/ML-App
